spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb:DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    plataform: h2
    username: sa
    password:
    diver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-plataform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        formmat_sql: true
    h2:
      console:
        enable: true
        path: /console    
  kafka:
     consumer:
        bootstrap-servers: localhost:9092
        group-id: group_id
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
     producer:
        bootstrap-servers: localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer